### PR TITLE
Simplify by overriding haskellPackages directly

### PR DESCRIPTION
**Pull request by vaibhavsagar**
I did a quick test with `nix-shell release.nix` and this seems to work the same as the old solution.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
In fact we could go one step further and override `haskellPackages` directly. I do that [here](https://github.com/gibiansky/IHaskell/blob/e4276ec382c215d323c83ba6836f9ab282b262ae/release.nix#L38-L65) for example and it works great :smile:.

**Comment by srdqty** [comment]
Yeah, this makes sense. This template is the first time I've used the config attribute to override things. I was looking at a couple examples in https://github.com/Gabriel439/haskell-nix and noticed he uses the config attribute and I was wondering if there is some benefit to modifying the config attribute. I don't have an answer atm.

**Comment by vaibhavsagar** [comment]
I think the effect is the same in all three cases. `packageOverrides` uses the overlays feature under the hood, and overriding `haskellPackages` directly accomplishes the same thing as the overlay (you can see this if you look at my second commit in isolation). AFAIK `haskell-nix` dates back to just before overlays were first introduced in Nixpkgs, which is probably why Gabriel uses them.

Happy to make any changes you want to this PR, and if you're more comfortable with your initial approach that's perfectly fine too.

**Comment by srdqty** [comment]
Yeah, I agree in this case it's the same. The thing I have in mind in particular is modifying the config for some non-haskell dependency a project might need. But I'm not very familiar with modifying the config for packages outside the nixos configuration.nix file. I definitely prefer your changes if it's still possible to do something like that when necessary.

**Comment by srdqty** [comment]
Actually, if I bring back updating the config if necessary, that doesn't mean I wouldn't want to use this for the haskell packages.

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request merged**
